### ISSUE TITLE
tsconfig.json error message

### ISSUE THREAD

**Issue by marvinrusinek** [annapogorelova/ng2-go-top-button#11]
Hi Anna,
I'm getting this error message (see below) when I added the "include" path to the tsconfig.json . I am also including my tsconfig.json file.  Please can you help me to resolve this error. I appreciate your help.
Thanks,
Marvin

**tsconfig.json:**
{
  "compileOnSave": false,
  "include": [
    "node_modules/ng2-go-top-button/src/**/*"
  ],
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "types": [
      "jasmine",
      "firebase"
    ]
  }
}

ng serve --port=5000
Your global Angular CLI version (1.6.3) is greater than your local
version (1.5.5). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
error TS18003: No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["node_modules/ng2-go-top-button/src/**/*"]' and 'exclude' paths were '["tes
t.ts","**/*.spec.ts"]'.

Error: error TS18003: No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["node_modules/ng2-go-top-button/src/**/*"]' and 'exclude' paths were
 '["test.ts","**/*.spec.ts"]'.

    at AngularCompilerPlugin._setupOptions (C:\Users\multi\Desktop\portfolioWeb\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:90:19)
    at new AngularCompilerPlugin (C:\Users\multi\Desktop\portfolioWeb\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:43:14)
    at _createAotPlugin (C:\Users\multi\Desktop\portfolioWeb\node_modules\@angular\cli\models\webpack-configs\typescript.js:77:16)
    at Object.getNonAotConfig (C:\Users\multi\Desktop\portfolioWeb\node_modules\@angular\cli\models\webpack-configs\typescript.js:100:19)
    at NgCliWebpackConfig.buildConfig (C:\Users\multi\Desktop\portfolioWeb\node_modules\@angular\cli\models\webpack-config.js:37:37)
    at Class.run (C:\Users\multi\Desktop\portfolioWeb\node_modules\@angular\cli\tasks\serve.js:71:98)
    at check_port_1.checkPort.then.port (C:\Users\multi\Desktop\portfolioWeb\node_modules\@angular\cli\commands\serve.js:123:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by annapogorelova** [comment]
Hi, @marvinrusinek. I don't see that you are including any other project source files in the **include** array of the tsconfig.json. You should probably refer to this issue [error TS18003](https://github.com/Microsoft/TypeScript/issues/17155). 

My tsconfig.json looks like this and compiles successfully:
`{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "include": [
    "src/**/*",
    "node_modules/ng2-go-top-button/src/**/*"
  ]
}
`
In the test project I'm using @angular/cli v1.6.8.
Let me know please if you still have this problem after modifying the tsconfig.json.
Thanks.

**Comment by annapogorelova** [comment]
Closing due to the absence of any activity here.
